name: deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.1.0
        with:
          node-version: 12.x

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache node_modules
        id: node-modules-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Cache Images
        id: image-cache
        uses: actions/cache@v2
        with:
          path: public/images
          key: ${{ runner.os }}-image-cache

      - run: yarn install --frozen-lockfile --audit

      - name: Build
        run: yarn build
        env:
          ORIGIN: https://therelease.news

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3.7.0-8
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: prod
          publish_dir: ./dist/out
          cname: therelease.news
