# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.1.0
        with:
          node-version: 12.x

      - name: Install libvips
        run: apt-get update -y --no-install-recommends --allow-unauthenticated --no-upgrade \
          && apt-get install -y \
          build-essential \
          wget \
          pkg-config \
          # libvips dependencies
          glib2.0-dev \
          libexpat1-dev \
          libtiff5-dev \
          libgsf-1-dev \
          libexif-dev \
          libgif-dev \
          librsvg2-dev \
          libpoppler-glib-dev \
          libtiff-dev \
          libpng-dev \
          && apt-get clean \
          && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile --audit

      - name: Build
        run: yarn build
        env:
          ORIGIN: https://therelease.news

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: master
          publish_dir: ./dist/out
          cname: therelease.news
